#! /usr/bin/env python3

# User Interface Entrance of UnivMaths System

    # Copyright (C) 2016 Zhang Chang-kai #
    # Contact via: phy.zhangck@gmail.com #
    # General Public License version 3.0 #

'''Internal User Interface of UnivMathSys'''


__version__ = "Internal 0.5.4.6"


import os
import sys
import logging
import readline


dir = os.path.split(os.path.realpath(__file__))[0]\
    + "/Package/UnivMathSys-Python.zip"
sys.path.insert(0, dir)


from UnivMathSys import *

print("")
print("Universal Mathematics System - "
    + __version__)
print("Python " + sys.version)


from Interpreter.compiler import Compile


def FileExec(FileName):
    with open(FileName, 'r') as file:
        block = False
        for line in file:
            if line is "\n":
                continue
            if not line.startswith(" "):
                if block is True:
                    block = False
                    exec(sntces)
                if line.startswith("#"):
                    continue
                if line.endswith(":\n"):
                    block = True
                    sntces = line
                    continue
                cmd = Compile(line)
                if cmd:
                    exec(cmd)
                else:
                    exec(line)
            else:
                sntces += line


def Interactive():
    block = False
    while True:
        if block is True:
            receive = input("... ")
            if receive is "":
                block = False
                exec(sntces)
                continue
            sntces += receive + "\n"
            continue
        else:
            receive = input(">>> ")
            if receive.endswith(":"):
                block = True
                sntces = receive + "\n"
                continue
            sntces = receive
        try:
            cmd = Compile(sntces)
            if cmd:
                exec(cmd)
            else:
                exec(sntces)
                try:
                    if sntces is not "":
                        eval("print(" + sntces + ")")
                except Exception:
                    pass
        except Exception:
            logging.exception("Exception Occurs")


if len(sys.argv) > 1:
    FileList = sys.argv[1:]
    for FileName in FileList:
        FileExec(FileName)
else:
    Interactive()


# End of Internal User Interface of UnivMathSys
